### PR TITLE
Fix and update test suite

### PR DESCRIPTION
**Pull request by wynksaiddestroy**
As outlined in #58 I updated RSpec and Capybara to their latest versions. Especially the RSpec version bump, required some bigger changes to the test applications. I haven't squashed/rebased the  individual commits into a big one, so you can track the changes more easily.

### CODE REVIEW

**Comment by techiferous** [comment]
Fabulous!  I'll look through the code and run the tests on my machine to verify everything is working.  Do you have any urgency around this pull request?  My personal life will be a lot busier than normal over the next few weeks so it could be a while before I get a chance to test this out but if it's holding you up I can certainly try to prioritize it.

**Comment by wynksaiddestroy** [comment]
There's no rush! Take your time for reviewing the fairly big changes and let me know if there's something I have missed.

**Comment by wynksaiddestroy** [comment]
Just a little reminder to look into the PR if you have minute to spare.

**Comment by techiferous** [comment]
Thanks for the reminder and your patience!  I'll get to it this week.

**Comment by techiferous** [comment]
:+1: Okay, I had a look at your changes and everything looks great.  This is fabulous.  Thanks for the TLC for the test suite.  I'd say proceed with adding your support for bootstrap 4 and when everything is ready I'll be happy to merge it all in and release a new version of the gem.

There is a larger issue and it's that the test suite is very cumbersome, complex and esoteric.  I'm very happy with the actual tests and the test coverage, but the process of targeting multiple environments (versions of Ruby and Rails) adds a lot of pain.  Tabulous was created before technologies like Docker or Travis CI got popular, which is one of the reasons for its Byzantine setup.  Do you happen to have any ideas about how to make the test suite much less cumbersome to use?  It has become a barrier to development.

**Comment by wynksaiddestroy** [comment]
Great. I think I’ll finish the support for Bootstrap within a week. Thanks for your appreciation.
Unfortunately I'm only a mediocre developer at best. So I don’t know how one could improve the inconvenient test suite.
Travis CI seems to be the most popular way of doing continuous integration these days. If I have a minute to spare, I'll have a look at the Travis CI docs and see what it has to offer.

**Comment by techiferous** [comment]
Cool, sounds good to me!  And don't feel any obligation to look into suggestions for better testing; I'm not trying to push that burden on to you.  I was just noticing that it's a problem for this project.

**Pull request closed without merging**
